In [2]:
import numpy as np
import pandas as pd

In [3]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [4]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [5]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns=columns)

Selection and indexing

In [6]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [7]:
df2[['Name',"Age"]]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

Creating a new column

In [8]:
df2["Designation"] = ["Doctor","Engineer","Doctor","Engineer"]

In [9]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

Remove Columns

In [10]:
df2.drop(["City","Salary"],axis=1,)

    Name  Age Designation
0   John   28      Doctor
1   Anna   34    Engineer
2  Peter   29      Doctor
3  Linda   42    Engineer

In [11]:
df2.drop(0,axis=0)

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000    Engineer
2  Peter   29  Berlin   62000      Doctor
3  Linda   42  London   85000    Engineer

Selecting Rows

In [12]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

In [13]:
df2.loc[0]

Name               John
Age                  28
City           New York
Salary            65000
Designation      Doctor
Name: 0, dtype: object

In [14]:
df.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [15]:
df.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

Selecting Subsets of Rows and Columns

In [16]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [17]:
df.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

Condtional Selection

In [18]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

In [19]:
# I only wnat to see those people whose age is above 30
df2[df2['Age']>30]

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000    Engineer
3  Linda   42  London   85000    Engineer

In [22]:
df2.drop("Designation",inplace=True,axis=1)

In [23]:
# I only want people whose age is above 30 and their city must be paris
df2[(df2['Age']>30) & (df2['City']=='Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000